name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  file_picker: ^8.1.2
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  flutter_localizations:
    sdk: flutter
  riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  auto_route: ^9.2.2

  intl: ^0.19.0
  share_plus: ^10.0.2
  flutter_native_splash: ^2.4.1
  intl_utils: ^2.8.7
  lottie: ^3.1.2
  
  paginated_list: ^1.2.3
  jwt_decoder: ^2.0.1
  dropdown_button2: ^2.3.9
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_intl:
  enabled: true


flutter_native_splash:
  image: assets/images/splash_image.png
  color: "#FFFFFF"
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/splash_image_android12.png
    icon_background_color: "#ffffff"

